# Generated by Django 4.2.3 on 2023-07-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_review_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
    ]
