# Generated by Django 4.2.3 on 2023-08-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contact_status_review_modify_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
    ]
